---
Haas:
  url: http://10.0.4.227:5000/
  device: itamco_Haas
  filter: //DataItem[@type='ASSET_CHANGED']

Dmg:
  url: http://10.0.4.227:5000/
  device: itamco_DMG
  filter: //DataItem[@type='ASSET_CHANGED']
  
  
#local:
#  url: http://localhost:5000/
#  device: mitsubishi_CNC
#  filter: //DataItem[@type='MEASUREMENT'or@type='PROGRAM'or@type='ASSET_CHANGED'or@type='EXECUTION']



