---
step:
  url: http://10.211.55.2:5000/
  device: VMC-3Axis
  filter: //DataItem[@type='ASSET_CHANGED']

#local:
#  url: http://localhost:5000/
#  device: mitsubishi_CNC
#  filter: //DataItem[@type='MEASUREMENT'or@type='PROGRAM'or@type='ASSET_CHANGED'or@type='EXECUTION']



