production:
  adapter: 'tinytds'
  host: 'VSV-SQL12-05'
  database: 'QUPID'

debug:
  adapter: 'tinytds'
  host: 'localhost'
  database: 'QUPID'
  username: 'vimana'
  password: 'password'

test:
  adapter: 'tinytds'
  host: 'localhost'
  database: 'QUPID_test'
  username: 'vimana'
  password: 'password'
  